Added common directory to store files common to the rdout and sync folders. This directory is copied over into the rdout and sync folders on the Pis

diff --git a/etc/copy_dirs b/etc/copy_dirs
--- a/etc/copy_dirs
+++ b/etc/copy_dirs
@@ -46,11 +46,18 @@ for IP in "${RDOUT_IPS[@]}"
 do
     echo "Copying $RDOUTDIR to $IP:$REMOTE_RDOUTDIR"
     rsync $RSYNC_FLAGS $RDOUTDIR $REMOTE_USR@$IP:~/ >> /dev/null
-
     # If something goes wrong, let the user know and exit
     if [ $? -ne 0 ]
     then
         echo "rsync with" $IP "failed - aborting."
+        exit 1
+    fi
+
+    scp -r $COMMONDIR/* $REMOTE_USR@$IP:$REMOTE_RDOUTDIR >> /dev/null
+    # If something goes wrong, let the user know and exit
+    if [ $? -ne 0 ]
+    then
+        echo "scp with" $IP "failed - aborting."
         exit 1
     fi
 done
@@ -59,10 +66,16 @@ for IP in "${SYNC_IPS[@]}"
 do
     echo "Copying $SYNCDIR to $IP:$REMOTE_SYNCDIR"
     rsync $RSYNC_FLAGS $SYNCDIR $REMOTE_USR@$IP:~/ >> /dev/null
-
     if [ $? -ne 0 ]
     then
         echo "rsync with" $IP "failed - aborting"
+        exit 1
+    fi
+
+    scp -r $COMMONDIR/* $REMOTE_USR@$IP:$REMOTE_RDOUTDIR >> /dev/null
+    if [ $? -ne 0 ]
+    then
+        echo "scp with" $IP "failed - aborting"
         exit 1
     fi
 done
