Moved run_rdout and run_sync to run_rdout_helper and run_sync_helper. rdout/src/new_rdout.c was moved to rdout_helper, and the same will soon be done for sync_debug. Also, a log file is now produced on each rdout and sync board. Will eventually transfer them to main repo at the end of the run

diff --git a/sync/run_sync_helper b/sync/run_sync_helper
--- a/sync/run_sync_helper
+++ b/sync/run_sync_helper
@@ -39,6 +39,7 @@ CTL_ORM=4
 # Other
 SYNC_ARGS="$PED"
 END_FILE="$SYNCDIR/stop.run.please"
+LOGFILE="$SYNCDIR/sync.log"
 
 
 
@@ -61,18 +62,26 @@ fi
 #################### FW INSTALL ####################
 # Sync ORM
 printf "\tProgramming CTL ORM\n"
-sudo $PROGEXE $SYNC_ORM < $SYNC_FW &> /dev/null
-# TODO CHECK SUCCESS
+sudo $PROGEXE $SYNC_ORM < $SYNC_FW >> $LOGFILE
+if [ $? -ne 0 ]
+then
+    printf "Programming failed. Aborting\n"
+    exit 1
+fi
 
 
 
 #################### COMPILE ####################
 # Compile (using the compile script)
-$COMPILE
-# TODO CHECK SUCCESS
+$COMPILE >> $LOGFILE
+if [ $? -ne 0 ]
+then
+    printf "Compilation failed. Aborting\n"
+    exit 1
+fi
 
 
 
 #################### RUN SYNC HELPER ####################
 # Run
-nohup sudo $SYNCEXE $SYNC_ARGS &> log.txt &
+nohup sudo $SYNCEXE $SYNC_ARGS &> $LOGFILE &
